# applications/wordpress.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jdhcexp/argocdtest.git
    path: overlays/production
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
