# overlays/production/kustomization.yaml
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
secretGenerator:
  - name: wordpress-secrets
    behavior: merge
    literals:
      - WORDPRESS_AUTH_KEY==)f3.9B^ag(~e@+{KD<Cy49-YK{~q0X<#V&=!Ix4G2Sy3O!Xb>Yru+57Aza16O/t
