# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all resource files here
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secrets.yaml
