apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
stringData:
  WORDPRESS_AUTH_KEY: "li9xi]F<}^mx<1Tj@eXGXTXrdtI78XRoy81PA<_k;O$!nyn|p53/_[:@21Z5ili7"
  WORDPRESS_SECURE_AUTH_KEY: "`_7qZ:eRtSp[r_x1;LQn.Zu[vh&]Q7,/5u}c%<n>9M@{elC-xXBQ9y0+h{|Q}f~)"
